language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install -U pip"
  - "pip install -U wheel"
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - nosetests --with-coverage --cover-package=category_encoders
after_success:
  - coveralls